### ISSUE TITLE
bb deploy is not deploying shared functions

### ISSUE THREAD

**Issue by mohdmusthafaneo** [appblocks-hub/BB-CLI#30]
When deploying a project using `bb deploy -env Production` and choosing a function block as the target, the shared functions are not getting packaged or used.

And even after deploying a function that doesn't require any shared function, the ALB link is not returning anything
![image](https://user-images.githubusercontent.com/121943295/222065775-bfb36a15-16a1-47d8-a074-bcff4dcde6d2.png)

But the AWS ECS cluster seems to be running healthy

**Comment by that-coder** [comment]
@devthalal can you take care of this?

**Comment by devthalal** [comment]
This issue with access to the site was related to AWS traffic since VPC Security Groups were not allowing inbound traffic from port 80 (the CLI function deployment container exposed the default port). Setting new inbound traffic from port 80 will fix the issue.

And the issue, shared functions are not deployed has been fixed next release

**Comment by that-coder** [comment]
closing the issue. fixed in 0.12.21
